version: '3'
services:
  broker-5:
    image: confluentinc/cp-kafka:latest
    container_name: broker-5
    ports:
      - "9095:9095"
      - "19095:19095"
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: '10.0.0.24:22181,10.0.0.24:22182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://10.0.0.147:9095,EXTERNAL://second.leeminkan.dev:19095
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  broker-6:
    image: confluentinc/cp-kafka:latest
    container_name: broker-6
    ports:
      - "9096:9096"
      - "19096:19096"
    environment:
      KAFKA_BROKER_ID: 6
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: '10.0.0.24:22181,10.0.0.24:22182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://10.0.0.147:9096,EXTERNAL://second.leeminkan.dev:19096
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL